//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uPV.ImageView.MediaBrowser {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("uPV.ImageView.MediaBrowser.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accession Number.
        /// </summary>
        internal static string ColumnHeadingAccessionNumber {
            get {
                return ResourceManager.GetString("ColumnHeadingAccessionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        internal static string ColumnHeadingAttachments {
            get {
                return ResourceManager.GetString("ColumnHeadingAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability.
        /// </summary>
        internal static string ColumnHeadingAvailability {
            get {
                return ResourceManager.GetString("ColumnHeadingAvailability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOB.
        /// </summary>
        internal static string ColumnHeadingDateOfBirth {
            get {
                return ResourceManager.GetString("ColumnHeadingDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete On.
        /// </summary>
        internal static string ColumnHeadingDeleteOn {
            get {
                return ResourceManager.GetString("ColumnHeadingDeleteOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string ColumnHeadingFirstName {
            get {
                return ResourceManager.GetString("ColumnHeadingFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideographic Name.
        /// </summary>
        internal static string ColumnHeadingIdeographicName {
            get {
                return ResourceManager.GetString("ColumnHeadingIdeographicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institution.
        /// </summary>
        internal static string ColumnHeadingInstitutionName {
            get {
                return ResourceManager.GetString("ColumnHeadingInstitutionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string ColumnHeadingLastName {
            get {
                return ResourceManager.GetString("ColumnHeadingLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modality.
        /// </summary>
        internal static string ColumnHeadingModality {
            get {
                return ResourceManager.GetString("ColumnHeadingModality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instances.
        /// </summary>
        internal static string ColumnHeadingNumberOfInstances {
            get {
                return ResourceManager.GetString("ColumnHeadingNumberOfInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient ID.
        /// </summary>
        internal static string ColumnHeadingPatientId {
            get {
                return ResourceManager.GetString("ColumnHeadingPatientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string ColumnHeadingPatientName {
            get {
                return ResourceManager.GetString("ColumnHeadingPatientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phonetic Name.
        /// </summary>
        internal static string ColumnHeadingPhoneticName {
            get {
                return ResourceManager.GetString("ColumnHeadingPhoneticName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referring Physician.
        /// </summary>
        internal static string ColumnHeadingReferringPhysician {
            get {
                return ResourceManager.GetString("ColumnHeadingReferringPhysician", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string ColumnHeadingServer {
            get {
                return ResourceManager.GetString("ColumnHeadingServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source AE.
        /// </summary>
        internal static string ColumnHeadingSourceAETitle {
            get {
                return ResourceManager.GetString("ColumnHeadingSourceAETitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station Name.
        /// </summary>
        internal static string ColumnHeadingStationName {
            get {
                return ResourceManager.GetString("ColumnHeadingStationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study Date.
        /// </summary>
        internal static string ColumnHeadingStudyDate {
            get {
                return ResourceManager.GetString("ColumnHeadingStudyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string ColumnHeadingStudyDescription {
            get {
                return ResourceManager.GetString("ColumnHeadingStudyDescription", resourceCulture);
            }
        }
    }
}
